export const SERVER_EVENTS = {
  REGISTERED: 'registered',
  QUIZ_READY: 'quiz-ready',
  NEW_QUESTION: 'new-question',
  UPDATE_LEADERBOARD: 'update-leaderboard',
  PLAYER_QUIZ_ENDED: 'player-quiz-ended',
  ALL_PLAYERS_FINISHED: 'all-players-finished',
  QUIZ_RESTARTED: 'quiz-restarted',
  QUIZ_ALREADY_STARTED: 'quiz-already-started',
  FINAL_LEADERBOARD: 'final-leaderboard',
  PLAYERS_COUNT: 'players-count',
  QUIZ_CREATED: 'quiz-created',
  QUIZZES_LIST: 'quizzes-list',
  QUESTION_ADDED: 'question-added',
  QUESTION_UPDATED: 'question-updated',
  QUIZ_UPDATED: 'quiz-updated',
  QUIZ_QUESTIONS: 'quiz-questions',
  ERROR: 'error',
};

export const CLIENT_EVENTS = {
  REGISTER: 'register',
  SUBMIT_ANSWER: 'submit-answer',
  TIME_UP: 'time-up',
  GET_NEXT_QUESTION: 'get-next-question',
  GET_FINAL_LEADERBOARD: 'get-final-leaderboard',
  ADMIN_LOGIN: 'admin-login',
  GET_QUIZZES: 'get-quizzes',
  CREATE_QUIZ: 'create-quiz',
  ADD_QUESTION: 'add-question',
  UPDATE_QUESTION: 'update-question',
  DELETE_QUESTION: 'delete-question',
  DELETE_QUIZ: 'delete-quiz',
  SELECT_QUIZ: 'select-quiz',
  START_QUIZ: 'start-quiz',
  RESTART_QUIZ: 'restart-quiz',
  GET_QUIZ_QUESTIONS: 'get-quiz-questions',
};
